# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: '18'
            cache: 'npm'
      - name: Switch branch to master
        uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        if: ${{ github.event_name == 'release' }}
        run: npm run build:prod
      - name: Setup AWS Credential
        if: ${{ github.event_name == 'release' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GithubActions
          role-skip-session-tagging: true
      - name: Setup AWS STS
        if: ${{ github.event_name == 'release' }}
        run: aws sts get-caller-identity
      - name: Deploy to S3
        if: ${{ github.event_name == 'release' }}
        run: aws s3 sync dist/ s3://mitrais-technology-radar-new --follow-symlinks --delete
